DROP TABLE IF EXISTS comment CASCADE;
DROP TABLE IF EXISTS post CASCADE;
DROP TABLE IF EXISTS follows CASCADE;
DROP TABLE IF EXISTS password CASCADE;
DROP TABLE IF EXISTS image CASCADE;
DROP TABLE IF EXISTS "user" CASCADE;

DROP SEQUENCE IF EXISTS postid CASCADE;
DROP SEQUENCE IF EXISTS commentid CASCADE;
DROP SEQUENCE IF EXISTS imageid CASCADE;